import "./globals.css";
import opensans from './assets/fonts/fonts.js'

export const metadata = {
  title: "Finchat AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={opensans.className}>{children}</body>
    </html>
  );
}
